routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
Route::get('/', 'Controller@welcome')->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/teachers/list', 'HomeController@teachers')->name('teachers');
Route::get('/subjects/list', 'HomeController@subjects')->name('subjects');
Route::get('/lessons/list', 'HomeController@lessons')->name('lessons');
Route::get('/tests/list', 'HomeController@tests')->name('tests');
Route::get('/lessons/test/{id}', 'TestController@test')->name('test');

Route::resource('teachers', 'TeacherController');
Route::resource('subjects', 'SubjectController');
Route::resource('lessons', 'LessonController');
Route::resource('tests', 'TestController');
Route::resource('results', 'ResultController');
Route::resource('comments', 'CommentController');
Route::resource('admin/users', 'UserController', ['except' => ['create', 'store', 'show']]);

app/Teacher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
    protected $fillable = ['subject_id', 'name', 'surname', 'email', 'resume', 'image'];

    public function subject()
    {
        return $this->belongsTo(Subject::class);
    }
}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use App\Events\CreateTeacherEvent;
use App\Events\UpdateTeacherEvent;
use App\Http\Requests\TeacherRequest;
use App\Subject;
use App\Teacher;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class TeacherController extends Controller
{
    public function index()
    {
        $teachers = Teacher::paginate();
        return view('teachers.index', compact('teachers'));
    }

    public function create()
    {
        $subjects = Subject::all();
        return view('teachers.create', compact('subjects'));
    }

    public function store(TeacherRequest $request)
    {
        $createTeacherEvent = new CreateTeacherEvent();
        $createTeacherEvent->setData($request->validated());
        event($createTeacherEvent);

        return redirect()->route('teachers.index');
    }

    public function show(Teacher $teacher)
    {
        $subjects = Subject::all();
        return view('teachers.view', ['subjects' => $subjects, 'teacher' => $teacher]);
    }

    public function edit(Teacher $teacher)
    {
        $subjects = Subject::all();
        return view('teachers.edit', ['teacher' => $teacher, 'subjects' => $subjects]);
    }

    public function update(Request $request, Teacher $teacher)
    {
        $updateTeacherEvent = new UpdateTeacherEvent();
        $updateTeacherEvent->setData($request->all());
        $updateTeacherEvent->setTeacher($teacher);
        event($updateTeacherEvent);
        return redirect()->route('teachers.index');
    }

    public function destroy(Teacher $teacher)
    {
        $teacher->delete();
        return redirect()->route('teachers.index');
    }
}

resources/views/teachers/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <form action="{{ route('teachers.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('POST')
            <div class="mb-3">
                <label for="name" class="form-label">Name</label>
                <input type="text" class="form-control" name="name" id="name" value="{{ old('name') }}">
            </div>
            <div class="mb-3">
                <label for="surname" class="form-label">Surname</label>
                <input type="text" class="form-control" name="surname" id="surname" value="{{ old('surname') }}">
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="email" class="form-control" name="email" id="email" value="{{ old('email') }}">
            </div>
            <div class="form-group">
                <label for="subject_id">Fanlar</label>
                <select class="form-control select2" style="width: 100%;" id="subject_id"
                        name="subject_id">
                    <option>Fanni tanlang</option>
                    @foreach($subjects as $subject)
                        <option @if(old('subject_id') == $subject->id) selected @endif
                            value="{{ $subject->id }}">{{ $subject->subject_name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="mb-3">
                <label for="resume" class="form-label">Resume</label>
                <input type="file" name="resume" id="resume" aria-describedby="inputGroupFileAddon04" aria-label="Upload">
            </div>
            <div class="mb-3">
                <label for="image" class="form-label mr-3">Photo</label>
                <input type="file" name="image" id="image" aria-describedby="inputGroupFileAddon04" aria-label="Upload">
            </div>
            <button type="submit" class="btn btn-primary">Add Teacher</button>
        </form>
    </div>
@endsection

resources/views/teachers/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <form action="{{ route('teachers.update', $teacher->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="mb-3">
                <label for="name" class="form-label">Name</label>
                <input type="text" class="form-control" name="name" id="name" value="{{ $teacher->name }}">
            </div>
            <div class="mb-3">
                <label for="surname" class="form-label">Surname</label>
                <input type="text" class="form-control" name="surname" id="surname" value="{{ $teacher->surname }}">
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="email" class="form-control" name="email" id="email" value="{{ $teacher->email }}">
            </div>
            <div class="form-group">
                <label for="subject_id">Fanlar</label>
                <select class="form-control select2" style="width: 100%;" id="subject_id"
                        name="subject_id">
                    <option>Fanni tanlang</option>
                    @foreach($subjects as $subject)
                        <option @if($teacher->subject_id == $subject->id) selected @endif
                            value="{{ $subject->id }}">{{ $subject->subject_name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="mb-3">
                <label for="resume" class="form-label">Resume</label>
                <input type="file" name="resume" id="resume" aria-describedby="inputGroupFileAddon04" aria-label="Upload" value="{{ $teacher->resume }}">
            </div>
            <div class="mb-3">
                <label for="image" class="form-label mr-3">Photo</label>
                <input type="file" name="image" id="image" aria-describedby="inputGroupFileAddon04" aria-label="Upload" value="{{ $teacher->image }}">
            </div>
            <button type="submit" class="btn btn-primary">Edit Teacher</button>
        </form>
    </div>
@endsection

resources/views/teachers/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Teachers</h1>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Surname</th>
                <th scope="col">Email</th>
                <th scope="col">Subject</th>
                <th scope="col">
                    <a href="{{ route('teachers.create') }}">
                        <button class="btn-sm btn-success" type="submit">Add Teacher</button>
                    </a>
                </th>
            </tr>
            </thead>
            <tbody>
            @foreach($teachers as $teacher)
                <tr>
                    <td>{{ $teacher->id }}</td>
                    <td>{{ $teacher->name }}</td>
                    <td>{{ $teacher->surname }}</td>
                    <td>{{ $teacher->email }}</td>
                    <td>{{ $teacher->subject->subject_name }}</td>
                    <td>
                        <a href="{{ route('teachers.edit', $teacher->id) }}">
                            <button class="btn-sm btn-primary fa fa-pencil" style=" margin-right: 6px;" type="submit">Edit</button>
                        </a>
                        <form action="{{ route('teachers.destroy', $teacher->id) }}" method="POST"  style="display: contents;">
                            @csrf
                            @method('DELETE')
                            <button class="btn-sm btn-danger fa fa-trash" type="submit" onclick="return confirm('Do you want to delete {{ $teacher->name }}?')">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{ $teachers->links() }}
    </div>
@endsection

resources/views/teachers/show.blade.php
@extends('layouts.apps')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><h1>{{ __('Teachers') }}</h1></div>
                    <div class="card-body">
                        <div class="container">
                            <div class="row">
                                @foreach($teachers as $teacher)
                                    <div class="col">
                                        <img src="../storage/{{ $teacher->image }}" class="img-fluid" alt="..." style="height:300px; width:500px">
                                        <h3 class="mt-4">
                                            <p class="card-text">Name: {{ $teacher->name }}</p>
                                            <p class="card-text">Surname: {{ $teacher->surname }}</p>
                                            <p class="card-text">Email: {{ $teacher->email }}</p>
                                            <p class="card-text">Subject: <a href="subjects/{{ $teacher->subject_id }}">{{ $teacher->subject->subject_name }}</a></p>
                                        </h3>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/teachers/view.blade.php
@extends('layouts.apps')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><h1>{{ __('Teachers') }}</h1></div>
                    <div class="card-body">
                        <div class="container">
                            <div class="row">
                                @foreach($teachers as $teacher)
                                    <div class="col">
                                        <img src="../storage/{{ $teacher->image }}" class="img-fluid" alt="..." style="height:300px; width:500px">
                                        <h3 class="mt-4">
                                            <p class="card-text">Name: {{ $teacher->name }}</p>
                                            <p class="card-text">Surname: {{ $teacher->surname }}</p>
                                            <p class="card-text">Email: {{ $teacher->email }}</p>
                                            <p class="card-text">Subject: <a href="subjects/{{ $teacher->subject_id }}">{{ $teacher->subject->subject_name }}</a></p>
                                        </h3>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection