routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
Route::get('/', 'Controller@welcome')->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/teachers/list', 'HomeController@teachers')->name('teachers');
Route::get('/subjects/list', 'HomeController@subjects')->name('subjects');
Route::get('/lessons/list', 'HomeController@lessons')->name('lessons');
Route::get('/tests/list', 'HomeController@tests')->name('tests');
Route::get('/lessons/test/{id}', 'TestController@test')->name('test');

Route::resource('teachers', 'TeacherController');
Route::resource('subjects', 'SubjectController');
Route::resource('lessons', 'LessonController');
Route::resource('tests', 'TestController');
Route::resource('results', 'ResultController');
Route::resource('comments', 'CommentController');
Route::resource('admin/users', 'UserController', ['except' => ['create', 'store', 'show']]);

app/Lesson.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Lesson extends Model
{
    protected $fillable = ['subject_id', 'lesson_name', 'video', 'duration', 'status'];

    public function subject()
    {
        return $this->belongsTo(Subject::class);
    }

    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }

    public function tests()
    {
        return $this->hasMany(Test::class);
    }

}

app/Http/Controllers/LessonController.php
<?php

namespace App\Http\Controllers;

use App\Events\CreateLessonEvent;
use App\Events\UpdateLessonEvent;
use App\Http\Requests\LessonRequest;
use App\Lesson;
use App\Subject;
use Illuminate\Http\Request;

class LessonController extends Controller
{
    public function index()
    {
        $lessons = Lesson::with('subject')->paginate();
        return view('lessons.index', compact('lessons'));
    }

    public function create()
    {
        $subjects = Subject::all();
        return view('lessons.create', compact('subjects'));
    }

    public function store(LessonRequest $request)
    {
        $commentEvent = new CreateLessonEvent();
        $commentEvent->setData($request->validated());
        event($commentEvent);

        return redirect()->route('lessons.index');

    }

    public function show(Lesson $lesson)
    {
        return view('lessons.show', ['lesson' => $lesson]);
    }

    public function edit(Lesson $lesson)
    {
        $subjects = Subject::all();
        return view('lessons.edit', ['lesson' => $lesson, 'subjects' => $subjects]);
    }

    public function update(Request $request, Lesson $lesson)
    {
        $updateLessonEvent = new UpdateLessonEvent();
        $updateLessonEvent->setData($request->all());
        $updateLessonEvent->setLesson($lesson);
        event($updateLessonEvent);
        return redirect()->route('lessons.index');
    }

    public function destroy($id)
    {
        //
    }
}

resources/views/lessons/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <form action="{{ route('lessons.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('POST')
            <div class="form-group">
                <label for="subject_id">Fanlar</label>
                <select class="form-control select2" style="width: 100%;" id="subject_id"
                        name="subject_id">
                    <option>Fanni tanlang</option>
                    @foreach($subjects as $subject)
                        <option value="{{ $subject->id }}">{{ $subject->subject_name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="mb-3">
                <label for="lesson_name" class="form-label">Name</label>
                <input type="text" class="form-control" name="lesson_name" id="lesson_name">
            </div>
            <div class="mb-3">
                <label for="video" class="form-label mr-3">Video</label><br>
                <input type="file" name="video" id="video" aria-describedby="inputGroupFileAddon04" aria-label="Upload">
            </div>
            <div class="mb-3">
                <label for="duration" class="form-label">Duration</label>
                <input type="text" class="form-control" name="duration" id="duration">
            </div>
            <div class="form-check mb-3">
                <input class="form-check-input" type="radio" name="status" id="status" value="0">
                <label class="form-check-label" for="status">
                    Free
                </label>
                <input class="form-check-input ml-4" type="radio" name="status" id="status" value="1">
                <label class="form-check-label ml-5" for="status">
                    Paid
                </label>
            </div>
            <button type="submit" class="btn btn-primary">Add Lesson</button>
        </form>
    </div>
@endsection

resources/views/lessons/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <form action="{{ route('lessons.update', $lesson->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label for="subject_id">Fanlar</label>
                <select class="form-control select2" style="width: 100%;" id="subject_id" name="subject_id">
                    <option>Fanni tanlang</option>
                    @foreach($subjects as $subject)
                        <option @if($lesson->subject_id == $subject->id) selected @endif
                        value="{{ $subject->id }}">{{ $subject->subject_name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="mb-3">
                <label for="lesson_name" class="form-label">Name</label>
                <input type="text" class="form-control" name="lesson_name" id="lesson_name" value="{{ $lesson->lesson_name }}">
            </div>
            <div class="mb-3">
                <label for="video" class="form-label mr-3">Video</label><br>
                <input type="file" name="video" id="video" value="{{ $lesson->video }}">
            </div>
            <div class="mb-3">
                <label for="duration" class="form-label">Duration</label>
                <input type="text" class="form-control" name="duration" id="duration" value="{{ $lesson->duration }}">
            </div>
            <div class="form-check mb-3">
                <input class="form-check-input" type="radio" name="status" id="status" value="0" @if($lesson->status == 0) checked @endif>
                <label class="form-check-label" for="status">
                    Free
                </label>
                <input class="form-check-input ml-4" type="radio" name="status" id="status" value="1" @if($lesson->status == 1) checked @endif>
                <label class="form-check-label ml-5" for="status">
                    Paid
                </label>
            </div>
            <button type="submit" class="btn btn-primary">Edit Lesson</button>
        </form>
    </div>
@endsection

resources/views/lessons/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <h1>Lesson</h1>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Subject Name</th>
                <th scope="col">Lesson Name</th>
                <th scope="col">Duration</th>
                <th scope="col">Status</th>
                <th scope="col">
                    <a href="{{ route('lessons.create') }}">
                        <button class="btn-sm btn-success" type="submit">Add Lesson</button>
                    </a>
                </th>
            </tr>
            </thead>
            <tbody>
            @foreach($lessons as $lesson)
                <tr>
                    <td>{{ $lesson->id }}</td>
                    <td>{{ $lesson->subject->subject_name }}</td>
                    <td>{{ $lesson->lesson_name }}</td>
                    <td>{{ $lesson->duration }}</td>
                    <td>{{ $lesson->status }}</td>
                    <td>
                        <a href="{{ route('lessons.edit', $lesson->id) }}">
                            <button class="btn-sm btn-primary fa fa-pencil" style=" margin-right: 6px;" type="submit">Edit</button>
                        </a>
                        <form action="{{ route('lessons.destroy', $lesson->id) }}" method="POST"  style="display: contents;">
                            @csrf
                            @method('DELETE')
                            <button class="btn-sm btn-danger fa fa-trash" type="submit" onclick="return confirm('Do you want to delete {{ $lesson->lesson_name }}?')">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{ $lessons->links() }}
    </div>
@endsection

resources/views/lessons/show.blade.php
@extends('layouts.apps')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><h1>{{ __('Lessons') }}</h1></div>
                    <div class="card-body">
                        <div class="container">
                            <div class="row">
                                @foreach($lesson->tests as $test)
                                    <div class="col mb-3">
                                        <video width="400" height="300" @if (auth()->user()->status != 0 || $lesson->status == 0) controls @endif>
                                            <source src="../storage/{{ $lesson->video }}">
                                        </video>
                                        <h6 class="mt-4">
                                            <p class="card-text">Lesson Name: {{ $lesson->lesson_name }} </p>
                                            <p class="card-text d-block">Subject Name: {{ $lesson->subject->subject_name }}</p>
                                            <p class="card-text">Duration: {{ $lesson->duration }}</p>
                                            <p class="card-text">Status: @if ($lesson->status == 0) Free @else Paid @endif</p>
                                            <p class="card-text">Tests: <a href="/lessons/test/{{$lesson->id}}">{{ $lesson->lesson_name }} </a></p>
                                        </h6>
                                        <form action="{{ route('comments.store') }}" method="POST">
                                            @csrf
                                            @method('POST')
                                            <div class="mb-3">
                                                <input type="hidden" name="lessonId" id="lessonId" value="{{ $lesson->id }}">
                                                <label for="body">Comments</label> {{ count($lesson->comments) }}
                                                @foreach($lesson->comments as $comment)
                                                    <p>&nbsp;&nbsp;{{ $comment->comment }}</p>
                                                @endforeach
                                                <textarea class="form-control" name="body" id="body" style=" min-width: 500px;"></textarea>
                                            </div>
                                            <button type="submit" class="btn btn-primary">Comment</button>
                                        </form>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/lessons/view.blade.php
@extends('layouts.apps')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><h1>{{ __('Lessons') }}</h1></div>
                    <div class="card-body">
                        <div class="container">
                            <div class="row">
                                @foreach($lessons as $lesson)
                                    <div class="col mb-3">
                                        <video width="400" height="300" @if (auth()->user()->status != 0 || $lesson->status == 0) controls @endif>
                                            <source src="../storage/{{ $lesson->video }}">
                                        </video>
                                        <h6 class="mt-4">
                                            <p class="card-text">Lesson Name:{{ $lesson->lesson_name }}</p>
                                            <p class="card-text">Tests: <a href="/lessons/test/{{$lesson->id}}">{{ $lesson->lesson_name }} </a></p>
                                            <p class="card-text d-block">Subject Name: {{ $lesson->subject->subject_name }}</p>
                                            <p class="card-text">Duration: {{ $lesson->duration }}</p>
                                            <p class="card-text">Status: @if ($lesson->status == 0) Free @else Paid @endif</p>
                                        </h6>
                                        <form action="{{ route('comments.store') }}" method="POST">
                                            @csrf
                                            @method('POST')
                                            <div class="mb-3">
                                                <input type="hidden" name="lessonId" id="lessonId" value="{{ $lesson->id }}">
                                                <label for="body">Comments</label> {{ count($lesson->comments) }}
                                                @foreach($lesson->comments as $comment)
                                                    <p>&nbsp;&nbsp;{{ $comment->comment }}</p>
                                                @endforeach
                                                <textarea class="form-control" name="body" id="body" style=" min-width: 500px;"></textarea>
                                            </div>
                                            <button type="submit" class="btn btn-primary">Comment</button>
                                        </form>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection