routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
Route::get('/', 'Controller@welcome')->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/teachers/list', 'HomeController@teachers')->name('teachers');
Route::get('/subjects/list', 'HomeController@subjects')->name('subjects');
Route::get('/lessons/list', 'HomeController@lessons')->name('lessons');
Route::get('/tests/list', 'HomeController@tests')->name('tests');
Route::get('/lessons/test/{id}', 'TestController@test')->name('test');

Route::resource('teachers', 'TeacherController');
Route::resource('subjects', 'SubjectController');
Route::resource('lessons', 'LessonController');
Route::resource('tests', 'TestController');
Route::resource('results', 'ResultController');
Route::resource('comments', 'CommentController');
Route::resource('admin/users', 'UserController', ['except' => ['create', 'store', 'show']]);

app/Subject.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Subject extends Model
{
    protected $fillable = ['subject_name', 'price'];

    public function teachers()
    {
        return $this->hasMany(Teacher::class);
    }

    public function lessons()
    {
        return $this->hasMany(Lesson::class);
    }

    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }
}

app/Http/Controllers/SubjectController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SubjectRequest;
use App\Subject;
use Illuminate\Http\Request;

class SubjectController extends Controller
{
    public function index()
    {
        $subjects = Subject::paginate();
        return view('subjects.index', compact('subjects'));
    }

    public function create()
    {
        return view('subjects.create');
    }

    public function store(SubjectRequest $request)
    {
        Subject::create($request->validated());
        return redirect()->route('subjects.index');
    }

    public function show(Subject $subject)
    {
        return view('subjects.show', ['subject' => $subject]);
    }

    public function edit(Subject $subject)
    {
        return view('subjects.edit', compact('subject'));
    }

    public function update(Request $request, Subject $subject)
    {
        $subject->update($request->all());
        return redirect()->route('subjects.index');
    }

    public function destroy(Subject $subject)
    {
        $subject->delete();
        return redirect()->route('subjects.index');
    }

}

resources/views/subjects/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <form action="{{ route('subjects.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('POST')
            <div class="mb-3">
                <label for="subject_name" class="form-label">Name</label>
                <input type="text" class="form-control" name="subject_name" id="subject_name">
            </div>
            <div class="mb-3">
                <label for="price" class="form-label">Price</label>
                <input type="text" class="form-control" name="price" id="price">
            </div>
            <button type="submit" class="btn btn-primary">Add Subject</button>
        </form>
    </div>
@endsection

resources/views/subjects/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <form action="{{ route('subjects.update', $subject->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="mb-3">
                <label for="subject_name" class="form-label">Name</label>
                <input type="text" class="form-control" name="subject_name" id="subject_name" value="{{ $subject->subject_name }}">
            </div>
            <div class="mb-3">
                <label for="price" class="form-label">Price</label>
                <input type="text" class="form-control" name="price" id="price" value=" {{ $subject->price }}">
            </div>
            <button type="submit" class="btn btn-primary">Edit Subject</button>
        </form>
    </div>
@endsection

resources/views/subjects/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <h1>Subjects</h1>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Subject Name</th>
                <th scope="col">Price</th>
                <th scope="col">
                    <a href="{{ route('subjects.create') }}">
                        <button class="btn-sm btn-success" type="submit">Create Subject</button>
                    </a>
                </th>
            </tr>
            </thead>
            <tbody>
            @foreach($subjects as $subject)
                <tr>
                    <td>{{ $subject->id }}</td>
                    <td>{{ $subject->subject_name }}</td>
                    <td>{{ $subject->price }}</td>
                    <td>
                        <a href="{{ route('subjects.edit', $subject->id) }}">
                            <button class="btn-sm btn-primary fa fa-pencil" style=" margin-right: 6px;" type="submit">Edit</button>
                        </a>
                        <form action="{{ route('subjects.destroy', $subject->id) }}" method="POST"  style="display: contents;">
                            @csrf
                            @method('DELETE')
                            <button class="btn-sm btn-danger fa fa-trash" type="submit" onclick="return confirm('Do you want to delete {{ $subject->name }}?')">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{ $subjects->links() }}
    </div>
@endsection

resources/views/subjects/show.blade.php
@extends('layouts.apps')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><h1>{{ $subject->subject_name }}</h1></div>
                    <div class="card-body">
                        <div class="container">
                            <div class="row">
                                @foreach($subject->lessons as $lesson)
                                    <div class="col">
                                        <h3 class="mt-4">
                                            <p class="card-text">Name: {{ $lesson->lesson_name }}</p>
                                            <video width="400" height="300" @if (auth()->user()->status != 0 || $lesson->status == 0) controls @endif>
                                                <source src="../storage/{{ $lesson->video }}">
                                            </video>
                                            <p class="card-text">Duration: {{ $lesson->duration }}</p>
                                            <p class="card-text">Status: @if($lesson->status == 0) Free @else Paid @endif</p>
                                            <p class="card-text">Tests: <a href="/lessons/test/{{$lesson->id}}">{{ $lesson->lesson_name }} </a></p>
                                        </h3>
                                        <form action="{{ route('comments.store') }}" method="POST">
                                            @csrf
                                            @method('POST')
                                            <div class="mb-3">
                                                <input type="hidden" name="subjectId" id="subjectId" value="{{ $subject->id }}">
                                                <label for="body">Comments</label> {{ count($subject->comments) }}
                                                @foreach($subject->comments as $comment)
                                                    <p>&nbsp;&nbsp;{{ $comment->comment }}</p>
                                                @endforeach
                                                <textarea class="form-control" name="body" id="body" style=" min-width: 500px;"></textarea>
                                            </div>
                                            <button type="submit" class="btn btn-primary">Comment</button>
                                        </form>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/subjects/view.blade.php
@extends('layouts.apps')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><h1>{{ __('Subjects') }}</h1></div>
                    <div class="card-body">
                        <div class="container">
                            <div class="row">
                                @foreach($subjects as $subject)
                                    <div class="col">
                                        <h3 class="mt-4">
                                            <p class="card-text">Name: <a href="{{ $subject->id }}">{{ $subject->subject_name }}</a></p>
                                            <p class="card-text">Price: {{ $subject->price }}$</p>
                                        </h3>
                                        <form action="{{ route('comments.store') }}" method="POST">
                                            @csrf
                                            @method('POST')
                                            <div class="mb-3">
                                                <input type="hidden" name="subjectId" id="subjectId" value="{{ $subject->id }}">
                                                <label for="body">Comments</label> {{ count($subject->comments) }}
                                                @foreach($subject->comments as $comment)
                                                    <p>&nbsp;&nbsp;{{ $comment->comment }}</p>
                                                @endforeach
                                                <textarea class="form-control" name="body" id="body" style=" min-width: 500px;"></textarea>
                                            </div>
                                            <button type="submit" class="btn btn-primary">Comment</button>
                                        </form>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection